// components/FitnessChart.vue
<template>
  <UCard class="bg-slate-900 border border-slate-700">
    <div class="p-4">
      <div class="flex justify-between items-center mb-2">
        <h3 class="text-xs font-bold text-slate-400 uppercase">Fitness / Generation</h3>
        <UBadge v-if="!isTrainingActive" color="yellow" variant="subtle" size="xs">
          Using Best Model
        </UBadge>
      </div>

      <div class="w-full" style="min-height: 100px">
        <VChart
          :option="chartOption"
          class="w-full"
          style="height: 100px"
        />
      </div>

      <div class="flex justify-between mt-2 text-xs font-mono text-slate-500">
        <span>Gen: <span class="text-white">{{ currentGen }}</span></span>
        <span>Best: <span class="text-teal-400">{{ bestFitness.toFixed(0) }}</span></span>
      </div>
    </div>
  </UCard>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { use } from 'echarts/core';
import { CanvasRenderer } from 'echarts/renderers';
import { LineChart } from 'echarts/charts';
import {
  TitleComponent,
  TooltipComponent,
  GridComponent
} from 'echarts/components';
import VChart from 'vue-echarts';

// Register ECharts components
use([
  CanvasRenderer,
  LineChart,
  TitleComponent,
  TooltipComponent,
  GridComponent
]);

interface Props {
  fitnessHistory: { gen: number; fitness: number }[];
  currentGen: number;
  bestFitness: number;
  isTrainingActive: boolean;
}

const props = defineProps<Props>();

const chartOption = computed(() => ({
  xAxis: {
    type: 'category',
    data: props.fitnessHistory.map(d => d.gen),
    show: false
  },
  yAxis: {
    type: 'value',
    show: false
  },
  tooltip: {
    backgroundColor: '#1e293b',
    borderColor: '#334155',
    textStyle: { color: '#fff', fontSize: 10 },
    formatter: (params: any) => {
      return `Gen ${params.data[0]}: ${params.data[1].toFixed(0)}`;
    }
  },
  series: [{
    data: props.fitnessHistory.map(d => [d.gen, d.fitness]),
    type: 'line',
    smooth: true,
    lineStyle: { color: '#2dd4bf', width: 2 },
    symbol: 'none',
    animationDuration: 300
  }],
  grid: { left: 0, right: 0, top: 0, bottom: 0 }
}));
</script>

// components/FitnessChart.tsx
/**
 * =============================================================================
 * FITNESS CHART - Fitness History Visualization
 * =============================================================================
 * 
 * Displays fitness progression over generations using a line chart.
 */

import React from 'react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { GameMode } from '../types';

interface FitnessChartProps {
  fitnessHistory: { gen: number; fitness: number }[];
  currentGen: number;
  bestFitness: number;
  isTrainingActive: boolean;
}

const FitnessChart: React.FC<FitnessChartProps> = ({
  fitnessHistory,
  currentGen,
  bestFitness,
  isTrainingActive
}) => {
  return (
    <div className="bg-slate-900 p-4 rounded-lg border border-slate-700 relative overflow-hidden">
      <div className="flex justify-between items-center mb-2">
        <h3 className="text-xs font-bold text-slate-400 uppercase">Fitness / Generation</h3>
        {!isTrainingActive && (
          <span className="text-[10px] px-2 py-0.5 bg-yellow-500/10 text-yellow-300 rounded border border-yellow-500/30">Using Best Model</span>
        )}
      </div>

      <div className="w-full" style={{ minHeight: 100 }}>
        <ResponsiveContainer width="100%" height={100}>
          <LineChart data={fitnessHistory}>
            <XAxis dataKey="gen" hide />
            <YAxis hide domain={['auto', 'auto']} />
            <Tooltip
              contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px', color: '#fff', fontSize: '10px' }}
              itemStyle={{ color: '#2dd4bf' }}
            />
            <Line type="monotone" dataKey="fitness" stroke="#2dd4bf" strokeWidth={2} dot={false} animationDuration={300} />
          </LineChart>
        </ResponsiveContainer>
      </div>

      <div className="flex justify-between mt-2 text-xs font-mono text-slate-500">
        <span>Gen: <span className="text-white">{currentGen}</span></span>
        <span>Best: <span className="text-teal-400">{bestFitness.toFixed(0)}</span></span>
      </div>
    </div>
  );
};

export default FitnessChart;
