// components/GameHUD.vue
<template>
  <div
    v-if="activeMatch"
    class="absolute top-4 left-4 right-4 flex justify-between text-xl font-bold font-mono z-10 drop-shadow-md pointer-events-none"
  >
    <!-- Left Fighter (P1) -->
    <div class="flex flex-col items-start">
      <span :class="[leftInfo.color, 'font-bold text-xs tracking-wider animate-pulse']">{{ leftInfo.label }}</span>
      <div class="w-32 h-4 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden">
        <div :class="['h-full', leftInfo.bar, 'transition-all duration-75']" :style="{ width: `${gameState.player1Health}%` }" />
      </div>
      <div class="w-32 h-2 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden mt-1">
        <div class="h-full bg-amber-400 transition-all duration-75" :style="{ width: `${gameState.player1Energy}%` }" />
      </div>
    </div>

    <!-- Center Info -->
    <div class="flex flex-col items-center pt-2">
      <template v-if="settings.gameMode === 'TRAINING'">
        <span class="text-slate-500 font-bold text-[10px] tracking-widest uppercase">ROUND {{ currentMatchIndex + 1 }}</span>
        <span class="text-slate-300 font-mono text-sm">{{ gameState.timeRemaining.toFixed(0) }}</span>
        <span class="text-teal-400 font-bold text-[9px] tracking-wider uppercase mt-1">
          {{ gameState.matchesUntilEvolution }} {{ gameState.matchesUntilEvolution === 1 ? 'MATCH' : 'MATCHES' }} TO EVOLVE
        </span>
      </template>
      <template v-else>
        <span class="text-white font-bold opacity-60 tracking-widest text-xs">VS</span>
        <span class="text-yellow-400 font-mono text-sm">{{ gameState.timeRemaining.toFixed(0) }}</span>
      </template>
    </div>

    <!-- Right Fighter (P2) -->
    <div class="flex flex-col items-end">
      <span :class="[rightInfo.color, 'font-bold text-xs tracking-wider animate-pulse']">{{ rightInfo.label }}</span>
      <div class="w-32 h-4 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden">
        <div :class="['h-full', rightInfo.bar, 'transition-all duration-75']" :style="{ width: `${gameState.player2Health}%` }" />
      </div>
      <div class="w-32 h-2 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden mt-1">
        <div class="h-full bg-amber-400 transition-all duration-75" :style="{ width: `${gameState.player2Energy}%` }" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { Fighter } from '~/services/GameEngine';
import type { GameState, TrainingSettings, GameMode } from '~/types';

interface Props {
  activeMatch: { p1: Fighter; p2: Fighter } | null;
  gameState: GameState;
  settings: TrainingSettings;
  currentMatchIndex: number;
}

const props = defineProps<Props>();

function getFighterInfo(f: Fighter, gameMode: GameMode, generation: number): { label: string; color: string; bar: string } {
  if (f.isCustom) {
    if (f.color === '#a855f7') return { label: 'SCRIPT A', color: 'text-purple-400', bar: 'bg-purple-400' };
    if (f.color === '#14b8a6') return { label: 'SCRIPT B', color: 'text-teal-400', bar: 'bg-teal-400' };
    return { label: 'CUSTOM', color: 'text-purple-400', bar: 'bg-purple-400' };
  }

  if (!f.isAi) {
    return { label: 'HUMAN', color: 'text-green-500', bar: 'bg-green-500' };
  }

  if (gameMode === 'TRAINING') {
    return { label: `GEN ${generation}`, color: 'text-blue-400', bar: 'bg-blue-500' };
  }
  return { label: 'AI', color: 'text-blue-500', bar: 'bg-blue-500' };
}

const leftInfo = computed(() => {
  if (!props.activeMatch) return { label: '', color: '', bar: '' };
  const p1 = props.activeMatch.p1;
  const p2 = props.activeMatch.p2;
  
  let info = getFighterInfo(p1, props.settings.gameMode, props.gameState.generation);
  
  if (props.settings.gameMode === 'TRAINING' && p1.isAi && p2.isAi && !p1.isCustom && !p2.isCustom) {
    info = { label: 'P1', color: 'text-red-500', bar: 'bg-red-500' };
  }
  
  return info;
});

const rightInfo = computed(() => {
  if (!props.activeMatch) return { label: '', color: '', bar: '' };
  const p1 = props.activeMatch.p1;
  const p2 = props.activeMatch.p2;
  
  let info = getFighterInfo(p2, props.settings.gameMode, props.gameState.generation);
  
  if (props.settings.gameMode === 'TRAINING' && p1.isAi && p2.isAi && !p1.isCustom && !p2.isCustom) {
    info = { label: 'P2', color: 'text-blue-500', bar: 'bg-blue-500' };
  }
  
  return info;
});
</script>

// components/GameHUD.tsx
/**
 * =============================================================================
 * GAME HUD - Heads-Up Display Component
 * =============================================================================
 * 
 * Displays fighter health bars, energy bars, labels, and match timer.
 * Shows different labels based on fighter type (Human, AI, Custom Script).
 */

import React from 'react';
import { Fighter } from '../services/GameEngine';
import { GameState, TrainingSettings, GameMode } from '../types';

interface GameHUDProps {
  activeMatch: { p1: Fighter; p2: Fighter } | null;
  gameState: GameState;
  settings: TrainingSettings;
  currentMatchIndex: number;
}

/**
 * Helper to determine fighter label and visual style
 */
function getFighterInfo(f: Fighter, gameMode: GameMode, generation: number): { label: string; color: string; bar: string } {
  if (f.isCustom) {
    if (f.color === '#a855f7') return { label: 'SCRIPT A', color: 'text-purple-400', bar: 'bg-purple-400' };
    if (f.color === '#14b8a6') return { label: 'SCRIPT B', color: 'text-teal-400', bar: 'bg-teal-400' };
    return { label: 'CUSTOM', color: 'text-purple-400', bar: 'bg-purple-400' };
  }

  // Human fighters (not AI, not custom)
  if (!f.isAi) {
    return { label: 'HUMAN', color: 'text-green-500', bar: 'bg-green-500' };
  }

  // AI fighters
  if (gameMode === 'TRAINING') {
    return { label: `GEN ${generation}`, color: 'text-blue-400', bar: 'bg-blue-500' };
  }
  return { label: 'AI', color: 'text-blue-500', bar: 'bg-blue-500' };
}

const GameHUD: React.FC<GameHUDProps> = ({ activeMatch, gameState, settings, currentMatchIndex }) => {
  if (!activeMatch) return null;

  const p1 = activeMatch.p1;
  const p2 = activeMatch.p2;

  let leftInfo = getFighterInfo(p1, settings.gameMode, gameState.generation);
  let rightInfo = getFighterInfo(p2, settings.gameMode, gameState.generation);

  // Override for AI vs AI training to show P1/P2 (only when both are AI)
  if (settings.gameMode === 'TRAINING' && p1.isAi && p2.isAi && !p1.isCustom && !p2.isCustom) {
    leftInfo = { label: 'P1', color: 'text-red-500', bar: 'bg-red-500' };
    rightInfo = { label: 'P2', color: 'text-blue-500', bar: 'bg-blue-500' };
  }

  return (
    <div className="absolute top-4 left-4 right-4 flex justify-between text-xl font-bold font-mono z-10 drop-shadow-md pointer-events-none">
      {/* Left Fighter (P1) */}
      <div className="flex flex-col items-start">
        <span className={`${leftInfo.color} font-bold text-xs tracking-wider animate-pulse`}>{leftInfo.label}</span>
        <div className="w-32 h-4 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden">
          <div className={`h-full ${leftInfo.bar} transition-all duration-75`} style={{ width: `${gameState.player1Health}%` }}></div>
        </div>
        <div className="w-32 h-2 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden mt-1">
          <div className="h-full bg-amber-400 transition-all duration-75" style={{ width: `${gameState.player1Energy}%` }}></div>
        </div>
      </div>

      {/* Center Info */}
      <div className="flex flex-col items-center pt-2">
        {settings.gameMode === 'TRAINING' ? (
          <>
            <span className="text-slate-500 font-bold text-[10px] tracking-widest uppercase">ROUND {currentMatchIndex + 1}</span>
            <span className="text-slate-300 font-mono text-sm">{gameState.timeRemaining.toFixed(0)}</span>
            <span className="text-teal-400 font-bold text-[9px] tracking-wider uppercase mt-1">
              {gameState.matchesUntilEvolution} {gameState.matchesUntilEvolution === 1 ? 'MATCH' : 'MATCHES'} TO EVOLVE
            </span>
          </>
        ) : (
          <>
            <span className="text-white font-bold opacity-60 tracking-widest text-xs">VS</span>
            <span className="text-yellow-400 font-mono text-sm">{gameState.timeRemaining.toFixed(0)}</span>
          </>
        )}
      </div>

      {/* Right Fighter (P2) */}
      <div className="flex flex-col items-end">
        <span className={`${rightInfo.color} font-bold text-xs tracking-wider animate-pulse`}>{rightInfo.label}</span>
        <div className="w-32 h-4 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden">
          <div className={`h-full ${rightInfo.bar} transition-all duration-75`} style={{ width: `${gameState.player2Health}%` }}></div>
        </div>
        <div className="w-32 h-2 bg-slate-800 rounded-sm border border-slate-600 overflow-hidden mt-1">
          <div className="h-full bg-amber-400 transition-all duration-75" style={{ width: `${gameState.player2Energy}%` }}></div>
        </div>
      </div>
    </div>
  );
};

export default GameHUD;
