// components/MatchConfiguration.vue
<template>
  <div class="space-y-4">
    <!-- Header & Training Toggle -->
    <div class="flex justify-between items-center bg-slate-900/50 p-2 rounded-lg border border-slate-700/50">
      <div class="flex items-center gap-2">
        <h2 class="text-xs font-bold text-slate-300 uppercase tracking-widest pl-2">
          Match Setup
        </h2>
        <UButton
          size="xs"
          color="neutral"
          variant="ghost"
          @click="onOpenInfo"
          title="Game Info & Help"
        >
          i
        </UButton>
      </div>

      <!-- Visual Training Toggle -->
      <div class="flex items-center gap-2">
        <span :class="['text-[10px] font-bold', isTrainingActive ? 'text-success' : 'text-muted']">
          {{ isTrainingActive ? 'TRAINING' : 'ARCADE' }}
        </span>
        <USwitch
          :model-value="isTrainingActive"
          @update:model-value="toggleTrainingMode"
          color="success"
        />
      </div>
    </div>

    <div :class="['grid gap-4', isTrainingActive ? 'grid-cols-1' : 'grid-cols-2']">
      <!-- Player 1 Selector -->
      <div class="space-y-1">
        <h2 class="text-[10px] font-bold text-red-400 uppercase tracking-widest flex justify-between">
          <span>Player 1 (Left)</span>
          <span v-if="settings.player1Type !== 'HUMAN'" class="text-[8px] bg-red-900/50 px-1 rounded text-red-200">AUTO</span>
        </h2>
        <div :class="['flex flex-col gap-1 p-1 rounded-lg', isMatchRunning ? 'bg-slate-900/50 opacity-50' : 'bg-slate-900']">
          <UButton
            v-for="type in currentPlayer1Types"
            :key="type"
            :color="settings.player1Type === type ? 'success' : 'neutral'"
            :variant="settings.player1Type === type ? 'solid' : 'outline'"
            size="xs"
            :disabled="isMatchRunning"
            @click="!isMatchRunning && setPlayer1Type(type)"
            class="text-[10px] font-bold"
          >
            {{ getPlayerTypeLabel(type) }}
          </UButton>
        </div>
      </div>

      <!-- Player 2 Selector - Only shown in ARCADE mode -->
      <div v-if="!isTrainingActive" class="space-y-1">
        <h2 class="text-[10px] font-bold text-blue-400 uppercase tracking-widest flex justify-between">
          <span>Player 2 (Right)</span>
          <span class="text-[8px] bg-blue-900/50 px-1 rounded text-blue-200">AUTO</span>
        </h2>
        <div class="flex flex-col gap-1 bg-slate-900 p-1 rounded-lg">
          <UButton
            v-for="type in currentPlayer2Types"
            :key="type"
            :color="settings.player2Type === type ? 'success' : 'neutral'"
            :variant="settings.player2Type === type ? 'solid' : 'outline'"
            size="xs"
            @click="setPlayer2Type(type)"
            class="text-[10px] font-bold"
          >
            {{ getPlayerTypeLabel(type) }}
          </UButton>
        </div>
      </div>

      <!-- Player 2 Info - Only shown in TRAINING mode -->
      <div v-if="isTrainingActive" class="space-y-1">
        <h2 class="text-[10px] font-bold text-blue-400 uppercase tracking-widest flex justify-between">
          <span>Player 2 (Right)</span>
          <span class="text-[8px] bg-blue-900/50 px-1 rounded text-blue-200">AI</span>
        </h2>
        <div class="flex flex-col gap-1 bg-slate-900/50 p-1 rounded-lg border border-slate-700">
          <div class="py-1.5 rounded-md text-[10px] font-bold text-slate-500 text-center">
            Always AI (Training)
          </div>
        </div>
      </div>
    </div>

    <!-- Edit Script Button - Always visible -->
    <UButton
      @click="onOpenScriptEditor"
      color="secondary"
      variant="solid"
      class="w-full"
      size="sm"
    >
      <UIcon name="i-heroicons-pencil-square" class="w-4 h-4" />
      Open Script Editor
    </UButton>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { TrainingSettings, GameState } from '~/types';

interface Props {
  settings: TrainingSettings;
  setSettings: (updater: TrainingSettings | ((prev: TrainingSettings) => TrainingSettings)) => void;
  gameState: GameState;
  onOpenScriptEditor: () => void;
  onOpenInfo: () => void;
}

const props = defineProps<Props>();

const isTrainingActive = computed(() => props.settings.gameMode === 'TRAINING');
const isMatchRunning = computed(() => isTrainingActive.value && props.settings.isRunning);

// Arcade mode: Player 1 can be Human or AI (no Chuck - Chuck is opponent only)
// Training mode: No Human, No Chuck (Chuck is ARCADE-exclusive)
const arcadePlayer1Types = ['HUMAN', 'SIMPLE_AI', 'CUSTOM_A', 'CUSTOM_B'] as const;
const trainingPlayer1Types = ['SIMPLE_AI', 'CUSTOM_A', 'CUSTOM_B'] as const;
// Player 2: Chuck only available in ARCADE mode
const arcadePlayer2Types = ['SIMPLE_AI', 'CHUCK_AI', 'CUSTOM_A', 'CUSTOM_B'] as const;
const trainingPlayer2Types = ['SIMPLE_AI', 'CUSTOM_A', 'CUSTOM_B'] as const;

// Use computed to dynamically select available types based on mode
const currentPlayer1Types = computed(() => 
  isTrainingActive.value ? trainingPlayer1Types : arcadePlayer1Types
);
const currentPlayer2Types = computed(() => 
  isTrainingActive.value ? trainingPlayer2Types : arcadePlayer2Types
);

const hasCustomScript = computed(() => {
  return props.settings.player1Type.includes('CUSTOM') || 
         props.settings.player2Type.includes('CUSTOM') || 
         props.settings.opponentType.includes('CUSTOM');
});

const toggleTrainingMode = () => {
  const newMode = props.settings.gameMode === 'ARCADE' ? 'TRAINING' : 'ARCADE';
  props.setSettings(prev => ({
    ...prev,
    gameMode: newMode,
    isRunning: false,
    ...(newMode === 'TRAINING' && {
      player1Type: prev.player1Type === 'HUMAN' ? 'SIMPLE_AI' : prev.player1Type,
      player2Type: 'SIMPLE_AI'
    })
  }));
};

const setPlayer1Type = (type: (typeof arcadePlayer1Types)[number] | (typeof trainingPlayer1Types)[number]) => {
  props.setSettings(s => ({
    ...s,
    player1Type: type,
    ...(type === 'HUMAN' && { simulationSpeed: 1 })
  }));
};

const setPlayer2Type = (type: (typeof arcadePlayer2Types)[number] | (typeof trainingPlayer2Types)[number]) => {
  props.setSettings(s => ({ ...s, player2Type: type }));
};

/** Get human-readable label for player type */
const getPlayerTypeLabel = (type: string): string => {
  switch (type) {
    case 'HUMAN': return 'HUMAN';
    case 'SIMPLE_AI': return 'SIMPLE AI';
    case 'CHUCK_AI': return 'CHUCK AI';
    case 'CUSTOM_A': return 'SCRIPT A';
    case 'CUSTOM_B': return 'SCRIPT B';
    default: return type;
  }
};
</script>

// components/MatchConfiguration.tsx
/**
 * =============================================================================
 * MATCH CONFIGURATION - Player Selection Component
 * =============================================================================
 * 
 * Handles player type selection (Human, AI, Custom Scripts) and training mode toggle.
 */

import React from 'react';
import { TrainingSettings, GameMode, GameState } from '../types';

interface MatchConfigurationProps {
  settings: TrainingSettings;
  setSettings: React.Dispatch<React.SetStateAction<TrainingSettings>>;
  gameState: GameState;
  onOpenScriptEditor: () => void;
  onOpenInfo: () => void;
}

const MatchConfiguration: React.FC<MatchConfigurationProps> = ({
  settings,
  setSettings,
  gameState,
  onOpenScriptEditor,
  onOpenInfo
}) => {
  const isTrainingActive = settings.gameMode === 'TRAINING';
  // Disable opponent changes when match is running in Training mode (not just active, but actually running)
  const isMatchRunning = isTrainingActive && settings.isRunning;

  const toggleTrainingMode = () => {
    const newMode = settings.gameMode === 'ARCADE' ? 'TRAINING' : 'ARCADE';
    setSettings(prev => ({
      ...prev,
      gameMode: newMode,
      isRunning: false,
      // Set defaults when switching to Training mode
      ...(newMode === 'TRAINING' && {
        player1Type: prev.player1Type || 'AI',
        player2Type: 'AI' // Player 2 is always AI in Training mode
      })
    }));
  };

  return (
    <div className="space-y-4">
      {/* Header & Training Toggle */}
      <div className="flex justify-between items-center bg-slate-900/50 p-2 rounded-lg border border-slate-700/50">
        <div className="flex items-center gap-2">
          <h2 className="text-xs font-bold text-slate-300 uppercase tracking-widest pl-2">
            Match Setup
          </h2>
          <button
            onClick={onOpenInfo}
            className="w-4 h-4 rounded-full border border-slate-500 text-[10px] flex items-center justify-center text-slate-400 hover:text-white hover:border-white transition-colors"
            title="Game Info & Help"
          >
            i
          </button>
        </div>

        {/* Visual Training Toggle */}
        <div className="flex items-center gap-2">
          <span className={`text-[10px] font-bold ${isTrainingActive ? 'text-blue-400' : 'text-slate-500'}`}>
            {isTrainingActive ? 'TRAINING' : 'SINGLE MATCH'}
          </span>
          <button
            onClick={toggleTrainingMode}
            className={`relative w-8 h-4 rounded-full transition-colors ${isTrainingActive ? 'bg-blue-600' : 'bg-slate-600'}`}
            title={isTrainingActive ? "Switch to Single Match" : "Switch to Population Evolution"}
          >
            <span
              className={`absolute top-0.5 w-3 h-3 bg-white rounded-full transition-transform ${isTrainingActive ? 'left-4.5' : 'left-0.5'}`}
              style={{ left: isTrainingActive ? '18px' : '2px' }}
            />
          </button>
        </div>
      </div>

      <div className={`grid gap-4 ${isTrainingActive ? 'grid-cols-1' : 'grid-cols-2'}`}>
        {/* Player 1 Selector */}
        <div className="space-y-1">
          <h2 className="text-[10px] font-bold text-red-400 uppercase tracking-widest flex justify-between">
            <span>Player 1 (Left)</span>
            {settings.player1Type !== 'HUMAN' && <span className="text-[8px] bg-red-900/50 px-1 rounded text-red-200">AUTO</span>}
          </h2>
          <div className={`flex flex-col gap-1 p-1 rounded-lg ${isMatchRunning ? 'bg-slate-900/50 opacity-50' : 'bg-slate-900'}`}>
            {(['HUMAN', 'AI', 'CUSTOM_A', 'CUSTOM_B'] as const).map(type => (
              <button
                key={type}
                onClick={() => {
                  if (!isMatchRunning) {
                    setSettings(s => ({ 
                      ...s, 
                      player1Type: type,
                      // When switching to HUMAN, set simulation speed to 1x
                      ...(type === 'HUMAN' && { simulationSpeed: 1 })
                    }));
                  }
                }}
                disabled={isMatchRunning}
                className={`py-1.5 rounded-md text-[10px] font-bold transition-all ${isMatchRunning ? 'cursor-not-allowed opacity-50' : ''} ${settings.player1Type === type ? 'bg-red-600 text-white shadow-lg' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}
              >
                {type === 'CUSTOM_A' ? 'SCRIPT A' : type === 'CUSTOM_B' ? 'SCRIPT B' : type}
              </button>
            ))}
          </div>
        </div>

        {/* Player 2 Selector - Only shown in ARCADE mode */}
        {!isTrainingActive && (
          <div className="space-y-1">
            <h2 className="text-[10px] font-bold text-blue-400 uppercase tracking-widest flex justify-between">
              <span>Player 2 (Right)</span>
              <span className="text-[8px] bg-blue-900/50 px-1 rounded text-blue-200">AUTO</span>
            </h2>
            <div className="flex flex-col gap-1 bg-slate-900 p-1 rounded-lg">
              {(['AI', 'CUSTOM_A', 'CUSTOM_B'] as const).map(type => (
                <button
                  key={type}
                  onClick={() => setSettings(s => ({ ...s, player2Type: type }))}
                  className={`py-1.5 rounded-md text-[10px] font-bold transition-all ${settings.player2Type === type ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}
                >
                  {type === 'CUSTOM_A' ? 'SCRIPT A' : type === 'CUSTOM_B' ? 'SCRIPT B' : type}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Player 2 Info - Only shown in TRAINING mode */}
        {isTrainingActive && (
          <div className="space-y-1">
            <h2 className="text-[10px] font-bold text-blue-400 uppercase tracking-widest flex justify-between">
              <span>Player 2 (Right)</span>
              <span className="text-[8px] bg-blue-900/50 px-1 rounded text-blue-200">AI</span>
            </h2>
            <div className="flex flex-col gap-1 bg-slate-900/50 p-1 rounded-lg border border-slate-700">
              <div className="py-1.5 rounded-md text-[10px] font-bold text-slate-500 text-center">
                Always AI (Training)
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Edit Script Button (only if scripts selected) */}
      {(settings.player1Type.includes('CUSTOM') || settings.player2Type.includes('CUSTOM') || settings.opponentType.includes('CUSTOM')) && (
        <button
          onClick={onOpenScriptEditor}
          className="w-full py-2 bg-slate-700 hover:bg-slate-600 border border-slate-600 rounded-lg text-xs font-bold text-slate-200 transition-all flex items-center justify-center gap-2 group"
        >
          <span className="text-lg group-hover:scale-110 transition-transform">✏️</span> Open Script Editor
        </button>
      )}
    </div>
  );
};

export default MatchConfiguration;
