// components/ScriptEditor.tsx
/**
 * =============================================================================
 * SCRIPT EDITOR - Monaco Code Editor Modal
 * =============================================================================
 * 
 * Full-screen modal overlay containing a Monaco Editor for writing custom
 * fighter AI scripts. Features:
 * - JavaScript syntax highlighting
 * - Error display
 * - Save to localStorage
 * - Export/Import JSON files
 * - Reset to default template
 * 
 * LAZY LOADING:
 * Monaco Editor (~2MB) is loaded lazily only when this component mounts.
 * This keeps the main bundle small until the user actually uses the editor.
 * 
 * =============================================================================
 */

import React, { useState, useEffect, useCallback, useRef, Suspense, lazy } from 'react';
import type { OnMount } from '@monaco-editor/react';
import {
    getDefaultTemplate,
    loadScript,
    saveScript,
    exportScript,
    importScript,
    compileScript
} from '../services/CustomScriptRunner';

// Lazy load Monaco Editor - only loads when component mounts
const Editor = lazy(() => import('@monaco-editor/react').then(mod => ({ default: mod.default })));

// Loading fallback for Monaco
const EditorFallback = () => (
    <div style={{
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#1e1e1e',
        color: '#888',
        gap: '12px'
    }}>
        <div style={{
            width: '40px',
            height: '40px',
            border: '3px solid #a855f7',
            borderTopColor: 'transparent',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite'
        }} />
        <span>Loading Code Editor...</span>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
);

// =============================================================================
// COMPONENT PROPS
// =============================================================================

interface ScriptEditorProps {
    isOpen: boolean;
    onClose: () => void;
    onSave: (code: string) => void;
}

// =============================================================================
// SCRIPT EDITOR COMPONENT
// =============================================================================

const ScriptEditor: React.FC<ScriptEditorProps> = ({ isOpen, onClose, onSave }) => {
    const [code, setCode] = useState<string>('');
    const [error, setError] = useState<string | null>(null);
    const [isSaving, setIsSaving] = useState(false);
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Load saved script or default template on open
    useEffect(() => {
        if (isOpen) {
            const savedCode = loadScript();
            setCode(savedCode || getDefaultTemplate());
            setError(null);
        }
    }, [isOpen]);

    // Validate code on change
    useEffect(() => {
        if (code) {
            const result = compileScript(code);
            setError(result.error);
        }
    }, [code]);

    // Handle editor mount - configure Monaco
    const handleEditorMount: OnMount = (editor, monaco) => {
        // Add custom type definitions for autocomplete
        monaco.languages.typescript.javascriptDefaults.addExtraLib(`
      interface FighterState {
        /** Horizontal position (0 = left edge, ~800 = right edge) */
        x: number;
        /** Vertical position (0 = top, ~380 = ground level) */
        y: number;
        /** Horizontal velocity (negative = left, positive = right) */
        vx: number;
        /** Vertical velocity (negative = up, positive = down) */
        vy: number;
        /** Current health points (0-100) */
        health: number;
        /** Current energy points (0-100) */
        energy: number;
        /** Current action state (0=idle, 1=move_left, 2=move_right, 3=jump, 4=crouch, 5=punch, 6=kick, 7=block) */
        state: number;
        /** Facing direction (-1 = left, 1 = right) */
        direction: -1 | 1;
        /** Frames until next action available */
        cooldown: number;
        /** Fighter hitbox width */
        width: number;
        /** Fighter hitbox height */
        height: number;
      }

      interface Actions {
        /** Move left */
        left: boolean;
        /** Move right */
        right: boolean;
        /** Jump */
        up: boolean;
        /** Crouch */
        down: boolean;
        /** Punch (action1) */
        action1: boolean;
        /** Kick (action2) */
        action2: boolean;
        /** Block (action3) */
        action3: boolean;
      }

      /**
       * Your fighter AI function - called 60 times per second
       * @param self Your fighter's current state
       * @param opponent Enemy fighter's current state
       * @returns Object with action booleans
       */
      declare function decide(self: FighterState, opponent: FighterState): Actions;
    `, 'fighter-types.d.ts');

        // Focus editor
        editor.focus();
    };

    // Save and close
    const handleSave = useCallback(() => {
        setIsSaving(true);
        saveScript(code);
        onSave(code);
        setIsSaving(false);
        onClose();
    }, [code, onSave, onClose]);

    // Reset to default template
    const handleReset = useCallback(() => {
        if (confirm('Reset to default template? Your changes will be lost.')) {
            const template = getDefaultTemplate();
            setCode(template);
            saveScript(template);
        }
    }, []);

    // Export script as JSON
    const handleExport = useCallback(() => {
        exportScript(code);
    }, [code]);

    // Import script from JSON file
    const handleImport = useCallback(() => {
        fileInputRef.current?.click();
    }, []);

    const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
            const content = event.target?.result as string;
            const importedCode = importScript(content);
            if (importedCode) {
                setCode(importedCode);
            } else {
                alert('Invalid script file. Please select a valid exported script.');
            }
        };
        reader.readAsText(file);

        // Reset input so same file can be selected again
        e.target.value = '';
    }, []);

    // Handle keyboard shortcuts
    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (!isOpen) return;

            // Escape to close
            if (e.key === 'Escape') {
                onClose();
            }
            // Ctrl/Cmd + S to save
            if ((e.ctrlKey || e.metaKey) && e.key === 's') {
                e.preventDefault();
                handleSave();
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [isOpen, onClose, handleSave]);

    if (!isOpen) return null;

    return (
        <div
            style={{
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                backgroundColor: 'rgba(0, 0, 0, 0.85)',
                zIndex: 1000,
                display: 'flex',
                flexDirection: 'column',
                padding: '20px',
            }}
        >
            {/* Header */}
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginBottom: '12px',
                color: 'white',
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <h2 style={{
                        margin: 0,
                        fontSize: '20px',
                        fontWeight: 'bold',
                        color: '#a855f7'
                    }}>
                        ✏️ Custom Fighter Script Editor
                    </h2>
                    <span style={{
                        fontSize: '12px',
                        color: '#94a3b8',
                        backgroundColor: '#1e293b',
                        padding: '4px 8px',
                        borderRadius: '4px'
                    }}>
                        JavaScript
                    </span>
                </div>
                <button
                    onClick={onClose}
                    style={{
                        background: 'none',
                        border: 'none',
                        color: '#94a3b8',
                        fontSize: '24px',
                        cursor: 'pointer',
                        padding: '4px 8px',
                    }}
                    title="Close (Esc)"
                >
                    ✕
                </button>
            </div>

            {/* Editor */}
            <div style={{
                flex: 1,
                borderRadius: '8px',
                overflow: 'hidden',
                border: '1px solid #334155'
            }}>
                <Suspense fallback={<EditorFallback />}>
                    <Editor
                        height="100%"
                        defaultLanguage="javascript"
                        theme="vs-dark"
                        value={code}
                        onChange={(value) => setCode(value || '')}
                        onMount={handleEditorMount}
                        options={{
                            minimap: { enabled: false },
                            fontSize: 14,
                            lineNumbers: 'on',
                            scrollBeyondLastLine: false,
                            automaticLayout: true,
                            tabSize: 2,
                            wordWrap: 'on',
                            padding: { top: 12 },
                        }}
                    />
                </Suspense>
            </div>

            {/* Footer */}
            <div style={{
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginTop: '12px',
                gap: '12px',
            }}>
                {/* Error Display */}
                <div style={{
                    flex: 1,
                    color: error ? '#ef4444' : '#22c55e',
                    fontSize: '13px',
                    fontFamily: 'monospace',
                    backgroundColor: '#1e293b',
                    padding: '8px 12px',
                    borderRadius: '6px',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    whiteSpace: 'nowrap',
                }}>
                    {error || '✓ Script is valid'}
                </div>

                {/* Buttons */}
                <div style={{ display: 'flex', gap: '8px' }}>
                    <button
                        onClick={handleReset}
                        style={{
                            padding: '8px 16px',
                            backgroundColor: '#475569',
                            color: 'white',
                            border: 'none',
                            borderRadius: '6px',
                            cursor: 'pointer',
                            fontSize: '13px',
                            fontWeight: '500',
                        }}
                    >
                        Reset
                    </button>
                    <button
                        onClick={handleImport}
                        style={{
                            padding: '8px 16px',
                            backgroundColor: '#475569',
                            color: 'white',
                            border: 'none',
                            borderRadius: '6px',
                            cursor: 'pointer',
                            fontSize: '13px',
                            fontWeight: '500',
                        }}
                    >
                        Import
                    </button>
                    <button
                        onClick={handleExport}
                        style={{
                            padding: '8px 16px',
                            backgroundColor: '#475569',
                            color: 'white',
                            border: 'none',
                            borderRadius: '6px',
                            cursor: 'pointer',
                            fontSize: '13px',
                            fontWeight: '500',
                        }}
                    >
                        Export
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={!!error || isSaving}
                        style={{
                            padding: '8px 20px',
                            backgroundColor: error ? '#475569' : '#a855f7',
                            color: 'white',
                            border: 'none',
                            borderRadius: '6px',
                            cursor: error ? 'not-allowed' : 'pointer',
                            fontSize: '13px',
                            fontWeight: '600',
                            opacity: error ? 0.5 : 1,
                        }}
                    >
                        {isSaving ? 'Saving...' : 'Save & Close'}
                    </button>
                </div>

                {/* Hidden file input for import */}
                <input
                    ref={fileInputRef}
                    type="file"
                    accept=".json"
                    onChange={handleFileChange}
                    style={{ display: 'none' }}
                />
            </div>
        </div>
    );
};

export default ScriptEditor;

// components/ScriptEditor.vue
<template>
  <UModal v-model:open="isOpen" fullscreen :ui="{ content: 'w-[98vw] h-[95vh] max-w-[98vw] max-h-[95vh]' }">
    <template #default>
      <!-- Modal is controlled programmatically -->
    </template>
    <template #content>
      <UCard class="w-full h-full flex flex-col">
      <!-- Header -->
      <template #header>
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-5">
            <h2 class="text-xl font-bold text-purple-400">
              ✏️ Custom Fighter Script Editor
            </h2>

            <!-- Slot Switcher Tabs -->
            <div class="flex gap-1 bg-slate-800 p-1 rounded-lg">
              <UButton
                :color="activeSlot === 'slot1' ? 'success' : 'neutral'"
                :variant="activeSlot === 'slot1' ? 'solid' : 'outline'"
                size="xs"
                @click="switchSlot('slot1')"
              >
                Script A
              </UButton>
              <UButton
                :color="activeSlot === 'slot2' ? 'success' : 'neutral'"
                :variant="activeSlot === 'slot2' ? 'solid' : 'outline'"
                size="xs"
                @click="switchSlot('slot2')"
              >
                Script B
              </UButton>
            </div>

            <UBadge color="gray" variant="subtle" size="sm">
              JavaScript
            </UBadge>
          </div>
          <UButton
            icon="i-heroicons-x-mark"
            color="neutral"
            variant="ghost"
            @click="onClose"
          />
        </div>
      </template>

      <!-- Editor -->
      <div ref="editorContainer" class="flex-1 min-h-[60vh] rounded-lg overflow-hidden border border-slate-700" />

      <!-- Footer -->
      <template #footer>
        <div class="flex justify-between items-center gap-3">
          <!-- Error Display -->
          <div
            :class="[
              'flex-1 text-sm font-mono p-2 rounded-lg',
              error ? 'text-red-500 bg-red-500/10' : 'text-green-500 bg-green-500/10'
            ]"
          >
            {{ error || '✓ Script is valid' }}
          </div>

          <!-- Buttons -->
          <div class="flex gap-2">
            <UButton
              @click="handleReset"
              color="neutral"
              variant="outline"
              size="sm"
            >
              Load Default
            </UButton>
            <UButton
              @click="handleImport"
              color="neutral"
              variant="outline"
              size="sm"
            >
              Import
            </UButton>
            <UButton
              @click="handleExport"
              color="neutral"
              variant="outline"
              size="sm"
            >
              Export
            </UButton>
            <UButton
              @click="handleSave"
              :disabled="!!error || isSaving"
              color="success"
              variant="solid"
              size="sm"
            >
              {{ isSaving ? 'Saving...' : 'Save & Close' }}
            </UButton>
          </div>

          <!-- Hidden file input for import -->
          <input
            ref="fileInputRef"
            type="file"
            accept=".json"
            class="hidden"
            @change="handleFileChange"
          />
        </div>
      </template>
      </UCard>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed, nextTick } from 'vue';
import loader from '@monaco-editor/loader';
import type { editor } from 'monaco-editor';
import {
  getDefaultTemplate,
  loadScript,
  saveScript,
  exportScript,
  importScript,
  compileScript
} from '~/services/CustomScriptRunner';

interface Props {
  modelValue: boolean;
  onSave?: (code: string) => void;
}

const props = withDefaults(defineProps<Props>(), {
  onSave: () => {}
});

const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  save: [code: string];
}>();

const isOpen = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value)
});

const code = ref<string>('');
const error = ref<string | null>(null);
const isSaving = ref(false);
const fileInputRef = ref<HTMLInputElement | null>(null);
const editorContainer = ref<HTMLDivElement | null>(null);
const activeSlot = ref<'slot1' | 'slot2'>('slot1');
let editorInstance: editor.IStandaloneCodeEditor | null = null;
let monacoInstance: typeof import('monaco-editor') | null = null;
const cleanupFunctions: Array<() => void> = [];
let editorInitialized = false;

const switchSlot = (slot: 'slot1' | 'slot2') => {
  activeSlot.value = slot;
};

// Initialize Monaco when modal opens
const initMonaco = async () => {
  if (editorInitialized || !editorContainer.value) return;
  
  try {
    monacoInstance = await loader.init();
    if (!monacoInstance) return;
    const monaco = monacoInstance;

    if (monaco.languages && monaco.languages.typescript) {
      const tsLang = monaco.languages.typescript as any;
      if (tsLang.javascriptDefaults && typeof tsLang.javascriptDefaults.addExtraLib === 'function') {
        tsLang.javascriptDefaults.addExtraLib(`
      interface FighterState {
        x: number;
        y: number;
        vx: number;
        vy: number;
        health: number;
        energy: number;
        state: number;
        direction: -1 | 1;
        cooldown: number;
        width: number;
        height: number;
      }

      interface Actions {
        left: boolean;
        right: boolean;
        up: boolean;
        down: boolean;
        action1: boolean;
        action2: boolean;
        action3: boolean;
      }

      declare function decide(self: FighterState, opponent: FighterState): Actions;
    `, 'fighter-types.d.ts');
      }
    }

    if (!monaco.editor) return;
    editorInstance = monaco.editor.create(editorContainer.value, {
      value: code.value,
      language: 'javascript',
      theme: 'vs-dark',
      minimap: { enabled: false },
      fontSize: 14,
      lineNumbers: 'on',
      scrollBeyondLastLine: false,
      automaticLayout: true,
      tabSize: 2,
      wordWrap: 'on',
      padding: { top: 12 }
    });

    editorInstance.onDidChangeModelContent(() => {
      code.value = editorInstance?.getValue() || '';
    });

    editorInstance.focus();
    editorInitialized = true;
  } catch (err) {
    console.error('Failed to load Monaco Editor:', err);
  }
};

watch([isOpen, activeSlot], async () => {
  if (isOpen.value) {
    code.value = loadScript(activeSlot.value);
    error.value = null;
    
    // Wait for DOM to be ready before initializing Monaco
    await nextTick();
    
    // Check if editor needs (re)initialization
    // The editor container may have been recreated when modal reopened
    const needsInit = !editorInitialized || 
                      !editorInstance || 
                      !editorContainer.value?.children.length;
    
    if (needsInit) {
      // Reset state for fresh initialization
      editorInitialized = false;
      editorInstance?.dispose();
      editorInstance = null;
      await initMonaco();
    }
    
    if (editorInstance) {
      editorInstance.setValue(code.value);
      editorInstance.focus();
    }
  }
});

watch(code, () => {
  if (code.value) {
    const result = compileScript(code.value);
    error.value = result.error || null;
  }
});

onMounted(() => {
  const handleKeyDown = (e: KeyboardEvent) => {
    if (!isOpen.value) return;
    if (e.key === 'Escape') {
      emit('update:modelValue', false);
    }
    if ((e.ctrlKey || e.metaKey) && e.key === 's') {
      e.preventDefault();
      handleSave();
    }
  };

  window.addEventListener('keydown', handleKeyDown);

  cleanupFunctions.push(() => {
    window.removeEventListener('keydown', handleKeyDown);
  });
});

// Top-level cleanup
onUnmounted(() => {
  cleanupFunctions.forEach(cleanup => cleanup());
  editorInstance?.dispose();
});

const handleSave = () => {
  isSaving.value = true;
  saveScript(code.value, activeSlot.value);
  props.onSave(code.value);
  emit('save', code.value);
  isSaving.value = false;
  emit('update:modelValue', false);
};

const handleReset = () => {
  if (confirm(`Load default template for ${activeSlot.value === 'slot1' ? 'Script A' : 'Script B'}? Your current code will be replaced.`)) {
    const template = getDefaultTemplate();
    code.value = template;
    if (editorInstance) {
      editorInstance.setValue(template);
    }
    saveScript(template, activeSlot.value);
  }
};

const handleExport = () => {
  exportScript(code.value);
};

const handleImport = () => {
  fileInputRef.value?.click();
};

const handleFileChange = (e: Event) => {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = (event) => {
    const content = event.target?.result as string;
    const importedCode = importScript(content);
    if (importedCode) {
      code.value = importedCode;
      if (editorInstance) {
        editorInstance.setValue(importedCode);
      }
    } else {
      alert('Invalid script file. Please select a valid exported script.');
    }
  };
  reader.readAsText(file);

  (e.target as HTMLInputElement).value = '';
};

const onClose = () => {
  emit('update:modelValue', false);
};
</script>
